server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/users/** 
        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/api/transactions/**
        - id: app
          uri: lb://app
          predicates:
            - Path=/api/app/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            
springdoc:
  swagger-ui:
    urls:
      - name: app
        url: /v3/api-docs/app
      - name: user
        url: /v3/api-docs/user
      - name: transaction
        url: /v3/api-docs/transaction
            
  
